import localFont from "next/font/local";
import "../globals.css";
import NavHead from "@/components/NavHead";

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Movie Db",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} px-16 mx-auto antialiased dark:bg-body bg-white font-[Sora] dark:text-white text-dark`}
      >
        <header>
          <NavHead />
        </header>
        <main className="">{children}</main>
      </body>
    </html>
  );
}
